Fix fake Patch
Because below error has occured:

pkg/client/clientset/versioned/typed/commonnetworkpolicies/v1alpha1/fake/fake_commonnetworkpolicy.go:126:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)